# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nomprod', models.CharField(max_length=80)),
                ('precioU', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descrip', models.TextField(blank=True)),
                ('nit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
        ),
    ]
